// src/features/quranRoots/roots.data.ts

export const CORE_QURAN_ROOTS = [
  "أكل", "أمر", "أمن", "أهل", "آيات", "بعد", "بدل", "بدأ", "بين", "بلغ",
  "برك", "برأ", "بشر", "بصر", "بغى", "بقى", "بني", "بعث", "بيع", "ترك",
  "تعلم", "تقوى", "توب", "ثم", "ثواب", "جعل", "جمع", "جاء", "جد", "جهد",
  "جري", "حسن", "حسب", "حفظ", "حشر", "حق", "حكم", "حمد", "حمل", "حيا",
  "خرج", "خلق", "خير", "خوف", "ذكر", "ذلك", "ذهب", "دخل", "درى", "دين",
  "ذنب", "رزق", "رسل", "ركع", "رفع", "رحم", "رشد", "رأى", "سبق", "سجد",
  "سير", "سلم", "سمي", "سكن", "سوء", "سوف", "سعي", "شكر", "شرك", "شهد",
  "شرع", "صدق", "صرف", "ضر", "ضمن", "ضعف", "طلب", "طوع", "طهر",
  "ظلم", "ظهر", "عبد", "علم", "عمل", "عقل", "عفو", "عرف", "عهد",
  "غفر", "غيب", "فتح", "فكر", "فصل", "فضل", "فعل", "فوز", "فطر",
  "قام", "قول", "قتل", "قدر", "قرب", "قسم", "كتب", "كبر", "كفر",
  "كشف", "كون", "كره", "لعل", "لعب", "لبس", "لقاء", "ملك", "مشي",
  "موت", "نصر", "نفق", "نجا", "نذر", "نعم", "نفس", "نهي", "نور",
  "وقع", "وجد", "وهب", "ولي", "وعد", "وزن", "وصل", "ود",
  "يصبر", "يقين", "يسر", "يمن", "يوم",
  "آمن", "ابتلى", "اتبع", "اتقى", "اجتبى", "احتسب",
  "اختار", "ادخل", "اذن", "ارسل", "استغفر", "استوى", "اشرك",
  "اصبر", "اصطفى", "اطاع", "اعبد", "اعلم", "افعل", "اقترب",
  "اقم", "اقرأ", "البس", "امن", "اله", "انزل", "انهى",
  "اهدى", "اوتي", "اولي", "بسط", "بهت", "تاب",
  "تذكر", "تبرك", "تبين", "تجنب", "تجاوز", "تحت",
  "تحمل", "تخوف", "تدبر", "تربص", "تزوج", "تزين",
  "ثقل", "جاهد", "جادل", "جلس", "جهر",
  "جوع", "حارب", "حب", "حذر", "حرص", "حمى", "حنف", "حور", "خاف",
  "خبر", "ختم", "خشي", "خلد", "دعا", "دم", "ذبح",
  "رب", "روح", "زكى", "زاد", "زهد", "سأل", "سبح",
  "سدد", "سر", "سلح", "سمع", "شبه", "شجر", "شعر", "شفي",
  "صبر", "صرع", "صوم", "صنع", "صيب",
  "ضحك", "ضيف", "ظن", "عدل", "غلب",
  "فدى", "قدم", "قرأ", "قسط", "قصد", "قوي",
  "كذب", "كرم", "كن", "لعن", "لين", "ميز",
  "نوى", "وفي",
];

export const ROOT_DICTIONARY: Record<
  string,
  { meaning: string; occurrences?: number; derivatives?: string[] }
> = {
  // Main Roots (Approximate Occurrences)
  "أكل": { meaning: "to eat", occurrences: 108, derivatives: ["أكول", "مأكول"] },
  "أمر": { meaning: "to command, matter", occurrences: 283, derivatives: ["أمر", "أوامر", "مأمور"] },
  "أمن": { meaning: "to be safe, believe", occurrences: 879, derivatives: ["أمان", "مؤمن", "أمين"] },
  "أهل": { meaning: "people, family", occurrences: 125, derivatives: ["أهل", "أهالي"] },
  "آيات": { meaning: "signs, verses", occurrences: 382, derivatives: ["آية"] },
  "بعد": { meaning: "after, far away", occurrences: 200, derivatives: ["بعيد", "بُعد"] },
  "بدل": { meaning: "to exchange, substitute", occurrences: 45, derivatives: ["تبديل", "بديل"] },
  "بدأ": { meaning: "to begin, originate", occurrences: 55, derivatives: ["بدء", "مبتدأ"] },
  "بين": { meaning: "between, to clarify", occurrences: 446, derivatives: ["بيان", "مُبين"] },
  "بلغ": { meaning: "to reach", occurrences: 45, derivatives: ["بلاغ", "بالغ"] },
  "برك": { meaning: "blessing", occurrences: 32, derivatives: ["بركة", "مبارك", "تبارك"] },
  "برأ": { meaning: "to create, free", occurrences: 23, derivatives: ["براءة", "بارئ"] },
  "بشر": { meaning: "human, glad tidings", occurrences: 125, derivatives: ["بشر", "بشارة", "مبشر"] },
  "بصر": { meaning: "sight, insight", occurrences: 148, derivatives: ["بصيرة", "مبصر"] },
  "بغى": { meaning: "to seek wrongfully, transgress", occurrences: 44, derivatives: ["بغي", "باغٍ"] },
  "بقى": { meaning: "to remain, endure", occurrences: 38, derivatives: ["بقاء", "باقٍ"] },
  "بني": { meaning: "to build", occurrences: 110, derivatives: ["بناء", "بنيان"] },
  "بعث": { meaning: "to send, resurrect", occurrences: 67, derivatives: ["بعث", "مبعوث"] },
  "بيع": { meaning: "to sell, trade", occurrences: 18, derivatives: ["بيع", "بائع"] },
  "ترك": { meaning: "to leave, abandon", occurrences: 63, derivatives: ["ترك", "تارك"] },
  "تعلم": { meaning: "to learn", occurrences: 12, derivatives: ["تعلم", "تعلّم"] },
  "تقوى": { meaning: "piety, consciousness of God", occurrences: 257, derivatives: ["متقي"] },
  "توب": { meaning: "to repent", occurrences: 87, derivatives: ["توبة", "تائب"] },
  "ثم": { meaning: "then, thereafter", occurrences: 348, derivatives: [] },
  "ثواب": { meaning: "reward", occurrences: 42, derivatives: ["مثوبة"] },
  "جعل": { meaning: "to make, appoint", occurrences: 346, derivatives: ["جاعل"] },
  "جمع": { meaning: "to gather", occurrences: 128, derivatives: ["جميع", "مجموع", "جامع"] },
  "جاء": { meaning: "to come", occurrences: 254, derivatives: ["جائي"] },
  "جد": { meaning: "striving, seriousness", occurrences: 18, derivatives: ["جهد", "اجتهاد"] },
  "جهد": { meaning: "struggle, effort", occurrences: 41, derivatives: ["جهاد", "مجاهد"] },
  "جري": { meaning: "to flow, run", occurrences: 55, derivatives: ["جرى", "جاري"] },
  "حسن": { meaning: "good, beautiful", occurrences: 194, derivatives: ["إحسان", "حسنة", "أحسن"] },
  "حسب": { meaning: "to count, think", occurrences: 87, derivatives: ["حساب", "حاسب"] },
  "حفظ": { meaning: "to protect, preserve", occurrences: 44, derivatives: ["حفظ", "حافظ"] },
  "حشر": { meaning: "to gather, resurrect", occurrences: 37, derivatives: ["حشر", "محشور"] },
  "حق": { meaning: "truth, right", occurrences: 285, derivatives: ["حق", "حقيقة"] },
  "حكم": { meaning: "to judge, rule", occurrences: 210, derivatives: ["حكم", "حكيم", "أحكام"] },
  "حمد": { meaning: "to praise", occurrences: 68, derivatives: ["حمد", "حميد", "محمود"] },
  "حمل": { meaning: "to carry, bear", occurrences: 84, derivatives: ["حمل", "حامل", "حَمّال"] },
  "حيا": { meaning: "life, to revive", occurrences: 183, derivatives: ["حياة", "حي", "أحياء"] },
  "خرج": { meaning: "to exit, go out", occurrences: 202, derivatives: ["خروج", "خارج"] },
  "خلق": { meaning: "to create", occurrences: 261, derivatives: ["خلق", "خالق", "مخلوق"] },
  "خير": { meaning: "good, better", occurrences: 176, derivatives: ["خيرات"] },
  "خوف": { meaning: "fear", occurrences: 124, derivatives: ["خوف", "خائف"] },
  "ذكر": { meaning: "to remember, mention", occurrences: 292, derivatives: ["ذكر", "ذاكر", "تذكير"] },
  "ذلك": { meaning: "that (demonstrative pronoun)", occurrences: 746, derivatives: [] },
  "ذهب": { meaning: "to go", occurrences: 88, derivatives: ["ذهاب"] },
  "دخل": { meaning: "to enter", occurrences: 161, derivatives: ["دخول", "مدخل"] },
  "درى": { meaning: "to know, perceive", occurrences: 28, derivatives: ["إدراك"] },
  "دين": { meaning: "religion, debt", occurrences: 99, derivatives: ["دين", "ديّان"] },
  "ذنب": { meaning: "sin", occurrences: 39, derivatives: ["ذنوب"] },
  "رزق": { meaning: "to provide", occurrences: 123, derivatives: ["رزق", "رازق", "أرزاق"] },
  "رسل": { meaning: "to send a messenger", occurrences: 513, derivatives: ["رسول", "رسالة"] },
  "ركع": { meaning: "to bow", occurrences: 13, derivatives: ["ركوع", "راكع"] },
  "رفع": { meaning: "to raise", occurrences: 65, derivatives: ["رفع", "رفيع"] },
  "رحم": { meaning: "mercy", occurrences: 335, derivatives: ["رحمة", "رحيم", "رحمن"] },
  "رشد": { meaning: "right guidance", occurrences: 19, derivatives: ["راشد"] },
  "رأى": { meaning: "to see", occurrences: 328, derivatives: ["رؤية", "رائي"] },
  "سبق": { meaning: "to precede, surpass", occurrences: 20, derivatives: ["سبق", "سابق"] },
  "سجد": { meaning: "to prostrate", occurrences: 92, derivatives: ["سجود", "مسجد"] },
  "سير": { meaning: "to travel, journey", occurrences: 28, derivatives: ["سير", "مسيرة"] },
  "سلم": { meaning: "peace, submission", occurrences: 140, derivatives: ["سلام", "إسلام", "مسلم"] },
  "سمي": { meaning: "name", occurrences: 120, derivatives: ["اسم", "أسماء", "تسمية"] },
  "سكن": { meaning: "to dwell, rest", occurrences: 69, derivatives: ["سكن", "سكينة", "مسكن"] },
  "سوء": { meaning: "evil, badness", occurrences: 132, derivatives: ["سيئة", "أسوأ"] },
  "سوف": { meaning: "soon, will (future marker)", occurrences: 104, derivatives: [] },
  "سعي": { meaning: "to strive, walk", occurrences: 30, derivatives: ["سعي", "ساعي"] },
  "شكر": { meaning: "to be thankful", occurrences: 75, derivatives: ["شكر", "شكور"] },
  "شرك": { meaning: "to associate (partners with God)", occurrences: 168, derivatives: ["شرك", "مشرك"] },
  "شهد": { meaning: "to witness", occurrences: 160, derivatives: ["شهادة", "شهيد", "شاهد"] },
  "شرع": { meaning: "law, legislate", occurrences: 31, derivatives: ["شريعة", "شارع"] },
  "صدق": { meaning: "truth, sincerity", occurrences: 155, derivatives: ["صادق", "صدق", "صديق"] },
  "صرف": { meaning: "to turn away, avert", occurrences: 30, derivatives: ["صرف", "مصروف"] },
  "ضر": { meaning: "harm, distress", occurrences: 77, derivatives: ["ضر", "ضرر"] },
  "ضمن": { meaning: "to guarantee", occurrences: 3, derivatives: ["ضمان"] },
  "ضعف": { meaning: "weakness, double", occurrences: 24, derivatives: ["ضعيف", "أضعاف"] },
  "طلب": { meaning: "to seek, request", occurrences: 45, derivatives: ["طلب", "طالب", "مطلوب"] },
  "طوع": { meaning: "willingly, voluntary", occurrences: 27, derivatives: ["طاعة", "مطواع"] },
  "طهر": { meaning: "purity", occurrences: 31, derivatives: ["طهارة", "طاهر", "تطهير"] },
  "ظلم": { meaning: "wrongdoing, darkness", occurrences: 315, derivatives: ["ظلم", "ظالم", "مظلوم"] },
  "ظهر": { meaning: "to appear, back", occurrences: 75, derivatives: ["ظهور", "ظاهر", "مظهر"] },
  "عبد": { meaning: "to worship, serve", occurrences: 279, derivatives: ["عبد", "عبادة", "معبود"] },
  "علم": { meaning: "to know, knowledge", occurrences: 854, derivatives: ["عليم", "عالم", "علم", "معلوم"] },
  "عمل": { meaning: "to do, work", occurrences: 360, derivatives: ["عمل", "عامل", "أعمال"] },
  "عقل": { meaning: "reason, intellect", occurrences: 49, derivatives: ["عقل", "عاقل"] },
  "عفو": { meaning: "to pardon, remit", occurrences: 35, derivatives: ["عفو", "عفُو"] },
  "عرف": { meaning: "to know, recognize", occurrences: 70, derivatives: ["معروف", "عارف"] },
  "عهد": { meaning: "covenant, agreement", occurrences: 45, derivatives: ["عهد", "عهود"] },
  "غفر": { meaning: "to forgive", occurrences: 234, derivatives: ["مغفرة", "غفور", "غفار"] },
  "غيب": { meaning: "unseen, hidden", occurrences: 55, derivatives: ["غيب", "غائب"] },
  "فتح": { meaning: "to open, grant victory", occurrences: 79, derivatives: ["فتح", "فتاح", "مفتاح"] },
  "فكر": { meaning: "to think", occurrences: 18, derivatives: ["فكر", "تفكير"] },
  "فصل": { meaning: "to separate, decide", occurrences: 45, derivatives: ["فصل", "فاصل"] },
  "فضل": { meaning: "favor, grace, merit", occurrences: 104, derivatives: ["فضل", "فضيلة"] },
  "فعل": { meaning: "to do", occurrences: 108, derivatives: ["فعل", "فاعل", "مفعول"] },
  "فوز": { meaning: "success, triumph", occurrences: 29, derivatives: ["فوز", "فائز"] },
  "فطر": { meaning: "to create, break fast", occurrences: 20, derivatives: ["فطرة", "فاطر"] },
  "قام": { meaning: "to stand, establish", occurrences: 663, derivatives: ["قيام", "قوام", "مقام"] },
  "قول": { meaning: "to say", occurrences: 1722, derivatives: ["قال", "قول", "مقولة"] },
  "قتل": { meaning: "to kill", occurrences: 170, derivatives: ["قتل", "قاتل"] },
  "قدر": { meaning: "power, decree", occurrences: 132, derivatives: ["قدر", "قدير", "مقدور"] },
  "قرب": { meaning: "nearness", occurrences: 96, derivatives: ["قرب", "قريب", "قربان"] },
  "قسم": { meaning: "to divide, oath", occurrences: 28, derivatives: ["قسمة", "قسّام"] },
  "كتب": { meaning: "to write", occurrences: 319, derivatives: ["كتاب", "كاتب", "مكتوب"] },
  "كبر": { meaning: "greatness", occurrences: 147, derivatives: ["كبير", "أكبر", "كبرياء"] },
  "كفر": { meaning: "to disbelieve, cover up", occurrences: 525, derivatives: ["كفر", "كافر", "كفّار"] },
  "كشف": { meaning: "to uncover, reveal", occurrences: 18, derivatives: ["كشف", "كاشف"] },
  "كون": { meaning: "to be, exist", occurrences: 1390, derivatives: ["كون", "كائن"] },
  "كره": { meaning: "dislike, aversion", occurrences: 40, derivatives: ["كراهية", "مكروه"] },
  "لعل": { meaning: "perhaps, so that", occurrences: 129, derivatives: [] },
  "لعب": { meaning: "to play", occurrences: 21, derivatives: ["لعب", "لاعب"] },
  "لبس": { meaning: "to wear, confuse", occurrences: 27, derivatives: ["لباس", "ملبس"] },
  "لقاء": { meaning: "to meet, encounter", occurrences: 65, derivatives: ["لقاء", "ملتقى"] },
  "ملك": { meaning: "to own, possess, rule", occurrences: 203, derivatives: ["ملك", "مالك", "مليك", "مملكة"] },
  "مشي": { meaning: "to walk", occurrences: 45, derivatives: ["مشي", "ماشي"] },
  "موت": { meaning: "death", occurrences: 165, derivatives: ["موت", "ميت"] },
  "نصر": { meaning: "to help", occurrences: 159, derivatives: ["نصر", "نصير", "نصرة"] },
  "نفق": { meaning: "to spend, circulate", occurrences: 74, derivatives: ["نفقة", "إنفاق"] },
  "نجا": { meaning: "to save, escape", occurrences: 49, derivatives: ["نجاة", "ناجٍ"] },
  "نذر": { meaning: "to warn", occurrences: 125, derivatives: ["إنذار", "نذير"] },
  "نعم": { meaning: "blessing, comfort", occurrences: 122, derivatives: ["نعمة", "نِعَم"] },
  "نفس": { meaning: "soul, self", occurrences: 298, derivatives: ["نفس", "أنفُس"] },
  "نهي": { meaning: "to forbid", occurrences: 38, derivatives: ["نهي", "ناهٍ"] },
  "نور": { meaning: "light", occurrences: 43, derivatives: ["نور", "منير"] },
  "وقع": { meaning: "to fall, occur", occurrences: 64, derivatives: ["وقوع", "واقع"] },
  "وجد": { meaning: "to find", occurrences: 108, derivatives: ["وجود", "واجد"] },
  "وهب": { meaning: "to grant, bestow", occurrences: 25, derivatives: ["هبة", "واهب"] },
  "ولي": { meaning: "ally, guardian, near", occurrences: 232, derivatives: ["ولي", "أولياء"] },
  "وعد": { meaning: "to promise", occurrences: 106, derivatives: ["وعد", "موعود"] },
  "وزن": { meaning: "to weigh", occurrences: 23, derivatives: ["وزن", "ميزان"] },
  "وصل": { meaning: "to join, reach", occurrences: 25, derivatives: ["وصل", "وصال"] },
  "ود": { meaning: "love, affection", occurrences: 18, derivatives: ["ودود"] },
  "يصبر": { meaning: "patience (verb form)", occurrences: 102, derivatives: ["صبر", "صابر"] },
  "يقين": { meaning: "certainty", occurrences: 28, derivatives: ["موقن"] },
  "يسر": { meaning: "ease", occurrences: 44, derivatives: ["يسر", "يسير"] },
  "يمن": { meaning: "blessing, right hand", occurrences: 15, derivatives: ["يمين", "أيمان"] },
  "يوم": { meaning: "day", occurrences: 475, derivatives: ["أيام"] },
  
  // Additional Roots (with occurrences)
  "آمن": { meaning: "to believe (Amana form IV)", occurrences: 879, derivatives: ["إيمان", "مؤمن"] },
  "ابتلى": { meaning: "to test, try", occurrences: 37, derivatives: ["بلاء", "مبتلى"] },
  "اتبع": { meaning: "to follow", occurrences: 175, derivatives: ["تابع", "اتباع"] },
  "اتقى": { meaning: "to be conscious of God (Taqwa)", occurrences: 257, derivatives: ["تقي", "متقي"] },
  "اجتبى": { meaning: "to choose, select", occurrences: 11, derivatives: ["اجتباء"] },
  "احتسب": { meaning: "to seek reward (from God)", occurrences: 1, derivatives: ["حسبة"] },
  "اختار": { meaning: "to choose", occurrences: 25, derivatives: ["اختيار"] },
  "ادخل": { meaning: "to make enter (Adkhala form IV)", occurrences: 161, derivatives: ["إدخال"] },
  "اذن": { meaning: "permission", occurrences: 100, derivatives: ["إذن", "مأذون"] },
  "ارسل": { meaning: "to send (Arsala form IV)", occurrences: 513, derivatives: ["إرسال", "رسول"] },
  "استغفر": { meaning: "to seek forgiveness", occurrences: 74, derivatives: ["استغفار", "مستغفر"] },
  "استوى": { meaning: "to settle, establish firmly", occurrences: 22, derivatives: ["استواء", "سَوِيّ"] },
  "اشرك": { meaning: "to associate (Ashraka form IV)", occurrences: 168, derivatives: ["إشراك", "مشرك"] },
  "اصبر": { meaning: "to be patient (Asbara form IV)", occurrences: 102, derivatives: ["صبر", "صابر"] },
  "اصطفى": { meaning: "to choose, select", occurrences: 23, derivatives: ["اصطفاء", "مصطفى"] },
  "اطاع": { meaning: "to obey", occurrences: 121, derivatives: ["طاعة", "مطيع"] },
  "اعبد": { meaning: "to worship (Amr form)", occurrences: 279, derivatives: ["عبادة", "عبد"] },
  "اعلم": { meaning: "to inform (A'lama form IV)", occurrences: 854, derivatives: ["إعلام"] },
  "افعل": { meaning: "to do (Amr form)", occurrences: 108, derivatives: ["فعل", "فاعل"] },
  "اقترب": { meaning: "to draw near", occurrences: 18, derivatives: ["قرب", "اقتِراب"] },
  "اقم": { meaning: "to establish (Aqama form IV)", occurrences: 663, derivatives: ["إقامة"] },
  "اقرأ": { meaning: "to read, recite (Amr form)", occurrences: 18, derivatives: ["قراءة", "قرآن"] },
  "البس": { meaning: "to dress, confuse (Almasa form IV)", occurrences: 27, derivatives: ["لباس"] },
  "امن": { meaning: "to believe (Amuna form I)", occurrences: 879, derivatives: ["أمن"] },
  "اله": { meaning: "God (Deity)", occurrences: 250, derivatives: ["إله", "آلهة"] },
  "انزل": { meaning: "to send down (Anzala form IV)", occurrences: 282, derivatives: ["إنزال", "منزل"] },
  "انهى": { meaning: "to forbid, stop", occurrences: 38, derivatives: ["نهاية", "نهي"] },
  "اهدى": { meaning: "to guide (Ahda form IV)", occurrences: 183, derivatives: ["هداية", "هاد"] },
  "اوتي": { meaning: "to be given (Passive of Ata form IV)", occurrences: 300, derivatives: ["إيتاء"] },
  "اولي": { meaning: "possessor of, those who", occurrences: 56, derivatives: ["أولياء", "ولي"] },
  "بسط": { meaning: "to stretch out, expand", occurrences: 18, derivatives: ["بسط", "بساط"] },
  "بهت": { meaning: "to be confounded, astonishment", occurrences: 4, derivatives: ["بهتان"] },
  "تاب": { meaning: "to repent (Taba form I)", occurrences: 87, derivatives: ["توبة", "تائب"] },
  "تذكر": { meaning: "to remember, heed", occurrences: 58, derivatives: ["تذكير", "ذكر"] },
  "تبرك": { meaning: "to seek blessing", occurrences: 32, derivatives: ["بركة", "مبارك"] },
  "تبين": { meaning: "to become clear", occurrences: 24, derivatives: ["بيان", "تبيان"] },
  "تجنب": { meaning: "to avoid", occurrences: 5, derivatives: ["جنابة"] },
  "تجاوز": { meaning: "to pass over, overlook", occurrences: 4, derivatives: ["جواز"] },
  "تحت": { meaning: "under, beneath", occurrences: 55, derivatives: [] },
  "تحمل": { meaning: "to bear, endure", occurrences: 6, derivatives: ["حمل", "تحمل"] },
  "تخوف": { meaning: "to fear, dread", occurrences: 4, derivatives: ["خوف"] },
  "تدبر": { meaning: "to ponder, reflect", occurrences: 4, derivatives: ["تدبر"] },
  "تربص": { meaning: "to wait, observe", occurrences: 17, derivatives: ["تربص"] },
  "تزوج": { meaning: "to marry", occurrences: 23, derivatives: ["زواج", "زوج"] },
  "تزين": { meaning: "to adorn oneself", occurrences: 9, derivatives: ["زينة"] },
  "ثقل": { meaning: "heavy, burden", occurrences: 23, derivatives: ["ثِقل", "ثقيل"] },
  "جاهد": { meaning: "to strive (Jahada form III)", occurrences: 41, derivatives: ["جهاد", "مجاهد"] },
  "جادل": { meaning: "to argue, dispute", occurrences: 11, derivatives: ["جدال", "مجادلة"] },
  "جلس": { meaning: "to sit", occurrences: 32, derivatives: ["مجلس"] },
  "جهر": { meaning: "to make public, loud", occurrences: 17, derivatives: ["جهر"] },
  "جوع": { meaning: "hunger", occurrences: 12, derivatives: ["جائع"] },
  "حارب": { meaning: "to fight, wage war", occurrences: 12, derivatives: ["حرب", "محارب"] },
  "حب": { meaning: "love", occurrences: 69, derivatives: ["محبة", "حبيب"] },
  "حذر": { meaning: "caution, beware", occurrences: 29, derivatives: ["حذر"] },
  "حرص": { meaning: "eagerness, greed", occurrences: 8, derivatives: ["حريص"] },
  "حمى": { meaning: "to protect", occurrences: 10, derivatives: ["حماية"] },
  "حنف": { meaning: "inclined (to truth), monotheist", occurrences: 12, derivatives: ["حنيف"] },
  "حور": { meaning: "to return, revert", occurrences: 12, derivatives: ["حور"] },
  "خاف": { meaning: "to fear (Khawifa form I)", occurrences: 124, derivatives: ["خوف", "خائف"] },
  "خبر": { meaning: "news, information", occurrences: 74, derivatives: ["خبير", "أخبار"] },
  "ختم": { meaning: "to seal, conclude", occurrences: 8, derivatives: ["خاتم", "ختام"] },
  "خشي": { meaning: "fear, reverence", occurrences: 48, derivatives: ["خشية", "خاشع"] },
  "خلد": { meaning: "eternal, to abide", occurrences: 27, derivatives: ["خلود", "خالد"] },
  "دعا": { meaning: "to call, pray", occurrences: 200, derivatives: ["دعوة", "داعي"] },
  "دم": { meaning: "blood", occurrences: 35, derivatives: ["دماء"] },
  "ذبح": { meaning: "to slaughter, sacrifice", occurrences: 12, derivatives: ["ذبح", "ذبيحة"] },
  "رب": { meaning: "Lord, Sustainer", occurrences: 970, derivatives: ["ربوبية"] },
  "روح": { meaning: "spirit", occurrences: 21, derivatives: ["روح", "أرواح"] },
  "زكى": { meaning: "to purify, grow", occurrences: 37, derivatives: ["زكاة", "زكي"] },
  "زاد": { meaning: "to increase", occurrences: 62, derivatives: ["زيادة"] },
  "زهد": { meaning: "to abstain, renounce", occurrences: 3, derivatives: ["زهد", "زاهد"] },
  "سأل": { meaning: "to ask", occurrences: 129, derivatives: ["سؤال", "سائل"] },
  "سبح": { meaning: "to glorify", occurrences: 90, derivatives: ["تسبيح", "سبحان"] },
  "سدد": { meaning: "to be upright, successful", occurrences: 3, derivatives: ["سداد"] },
  "سر": { meaning: "secret", occurrences: 25, derivatives: ["أسرار"] },
  "سلح": { meaning: "to arm", occurrences: 1, derivatives: ["سلاح"] },
  "سمع": { meaning: "to hear", occurrences: 183, derivatives: ["سمع", "سميع", "مسموع"] },
  "شبه": { meaning: "similarity", occurrences: 11, derivatives: ["شبه", "تشابه"] },
  "شجر": { meaning: "tree", occurrences: 26, derivatives: ["شجرة", "أشجار"] },
  "شعر": { meaning: "poetry, feeling", occurrences: 29, derivatives: ["شعر", "شاعر"] },
  "شفي": { meaning: "to cure, heal", occurrences: 8, derivatives: ["شفاء"] },
  "صبر": { meaning: "patience", occurrences: 102, derivatives: ["صبر", "صابر"] },
  "صرع": { meaning: "to throw down, fall", occurrences: 5, derivatives: ["صرعة"] },
  "صوم": { meaning: "fasting", occurrences: 13, derivatives: ["صوم", "صيام"] },
  "صنع": { meaning: "to manufacture, make", occurrences: 17, derivatives: ["صنع", "صناعة"] },
  "صيب": { meaning: "rain, to hit right", occurrences: 8, derivatives: ["صواب"] },
  "ضحك": { meaning: "to laugh", occurrences: 10, derivatives: ["ضحك"] },
  "ضيف": { meaning: "guest", occurrences: 13, derivatives: ["ضيافة"] },
  "ظن": { meaning: "to think, assume", occurrences: 69, derivatives: ["ظن", "ظنون"] },
  "عدل": { meaning: "justice, fairness", occurrences: 28, derivatives: ["عدل", "عادل"] },
  "غلب": { meaning: "to overcome, conquer", occurrences: 20, derivatives: ["غلبة", "غالب"] },
  "فدى": { meaning: "to ransom, redeem", occurrences: 5, derivatives: ["فداء"] },
  "قدم": { meaning: "to precede, put forward", occurrences: 57, derivatives: ["قُدُم", "مُقدّم"] },
  "قرأ": { meaning: "to read, recite (Qara'a form I)", occurrences: 88, derivatives: ["قراءة", "قرآن"] },
  "قسط": { meaning: "justice, share", occurrences: 13, derivatives: ["قسط", "مُقسِط"] },
  "قصد": { meaning: "to aim, moderation", occurrences: 8, derivatives: ["قصد", "مقتصد"] },
  "قوي": { meaning: "strength", occurrences: 25, derivatives: ["قوة", "قوي"] },
  "كذب": { meaning: "to lie, deny", occurrences: 110, derivatives: ["كذب", "كاذب"] },
  "كرم": { meaning: "generosity, nobility", occurrences: 17, derivatives: ["كرم", "كريم"] },
  "كن": { meaning: "to be (Kun - Be!)", occurrences: 1390, derivatives: ["كائن", "كون"] },
  "لعن": { meaning: "to curse", occurrences: 41, derivatives: ["لعنة", "ملعون"] },
  "لين": { meaning: "softness, gentleness", occurrences: 5, derivatives: ["لين", "ليّن"] },
  "ميز": { meaning: "to distinguish, separate", occurrences: 12, derivatives: ["تمييز", "مميز"] },
  "نوى": { meaning: "intention", occurrences: 3, derivatives: ["نوايا"] },
  "وفي": { meaning: "to fulfill (a promise)", occurrences: 45, derivatives: ["وفاء", "وفي"] }
};